version: '3.8'

services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    container_name: hokiguessr-nginx
  server:
      image: hokiguessr-backend-prod
      build: ./server
      ports:
        - 5000:5000
      environment:
        - DB_HOST=db
        - DB_USER=root
        - DB_PASSWORD=example
        - DB_NAME=hokiguessr
        - JWT_SECRET=verysecretjwt
        - REDIS_URL=redis://redis:6379
      container_name: hokiguessr-backend-prod
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --init-file /docker-entrypoint-initdb.d/init-db.sql
    restart: always
    volumes:
      - ./server/mysql_data:/var/lib/mysql
      - ./server/init-db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: hokiguessr
    ports:
      - 3306:3306
    container_name: hokiguessr-db-prod
  redis:
    image: redis
    ports:
      - 6378:6379
    command: ['redis-server', '--appendonly', 'yes'] # Overwrite the CMD
    volumes:
      - ./server/redis_data:/data
    container_name: hokiguessr-redis
  web:
    image: hokiguessr-frontend-prod
    build: ./web
    ports:
      - 3000:80
    environment:
      - REACT_APP_API_URL=/api
    container_name: hokiguessr-frontend-prod
