version: '3.8'

services:
  server:
      image: hokiguessr-backend
      build:
        context: ./server
        dockerfile: dev.Dockerfile
      volumes:
        - ./server:/usr/src/app
      ports:
        - 5000:5000
      environment:
        - DB_HOST=db
        - DB_USER=root
        - DB_PASSWORD=example
        - DB_NAME=hokiguessr
        - JWT_SECRET=verysecretjwt
        - REDIS_URL=redis://redis:6379
      container_name: hokiguessr-backend
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --init-file /docker-entrypoint-initdb.d/init-db.sql
    restart: always
    volumes:
      - ./server/mysql_data:/var/lib/mysql
      - ./server/init-db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: hokiguessr
    ports:
      - 3306:3306
    container_name: hokiguessr-db
  redis:
    image: redis
    ports:
      - 6378:6379
    command: ['redis-server', '--appendonly', 'yes'] # Overwrite the CMD
    volumes:
      - ./server/redis_data:/data
    container_name: hokiguessr-redis
  web:
    image: hokiguessr-frontend
    build:
      context: ./web
      dockerfile: dev.Dockerfile
    volumes:
      - ./web:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    container_name: hokiguessr-frontend
