const noLiveGames = {
  games: [],
};

const liveGamesNoGoal = {
  games: [
    {
      id: 1337,
      season: 2022,
      start: '2021-12-20T16:30:00Z',
      homeTeam: {
        teamId: '362185137:tappara',
        teamPlaceholder: null,
        goals: 0,
        timeOut: null,
        goalEvents: [],
        penaltyEvents: [],
        goalKeeperEvents: [],
        goalKeeperChanges: [],
        powerplayInstances: 3,
        powerplayGoals: 0,
        shortHandedInstances: 2,
        shortHandedGoals: 0,
      },
      awayTeam: {
        teamId: '859884935:kalpa',
        teamPlaceholder: null,
        goals: 0,
        timeOut: 3436,
        goalEvents: [],
        penaltyEvents: [
          {
            playerId: 31110600,
            suffererPlayerId: 31110600,
            logTime: '2021-12-20T16:40:56Z',
            gameTime: 318,
            period: 1,
            penaltyBegintime: 318,
            penaltyEndtime: 438,
            penaltyFaultName: 'Koukkaaminen',
            penaltyFaultType: 'KOU',
            penaltyInfo: '',
            penaltyMinutes: 2,
          },
          {
            playerId: 25057054,
            suffererPlayerId: 25057054,
            logTime: '2021-12-20T17:29:03Z',
            gameTime: 1648,
            period: 2,
            penaltyBegintime: 1648,
            penaltyEndtime: 1768,
            penaltyFaultName: 'Huitominen',
            penaltyFaultType: 'HUI',
            penaltyInfo: '',
            penaltyMinutes: 2,
          },
          {
            playerId: 24558127,
            suffererPlayerId: 24558127,
            logTime: '2021-12-20T18:52:54Z',
            gameTime: 2326,
            period: 2,
            penaltyBegintime: 2326,
            penaltyEndtime: 2446,
            penaltyFaultName: 'Kampitus',
            penaltyFaultType: 'KAM',
            penaltyInfo: '',
            penaltyMinutes: 2,
          },
        ],
        goalKeeperEvents: [
          {
            playerId: 60328138,
            beginTime: 3436,
            emptyNet: 1,
            endTime: 3539,
            logTime: '2021-12-20T18:39:03Z',
            gameTime: 3436,
            period: 3,
          },
          {
            playerId: 60328138,
            beginTime: 3539,
            emptyNet: 0,
            endTime: 3600,
            logTime: '2021-12-20T18:40:00Z',
            gameTime: 3539,
            period: 3,
          },
        ],
        goalKeeperChanges: [],
        powerplayInstances: 2,
        powerplayGoals: 0,
        shortHandedInstances: 3,
        shortHandedGoals: 0,
      },
      winningShotCompetitionEvents: [],
      periods: [
        {
          index: 1,
          homeTeamGoals: 2,
          awayTeamGoals: 0,
          category: 'NORMAL',
          startTime: 0,
          endTime: 1200,
        },
        {
          index: 2,
          homeTeamGoals: 1,
          awayTeamGoals: 2,
          category: 'NORMAL',
          startTime: 1200,
          endTime: 2400,
        },
        {
          index: 3,
          homeTeamGoals: 1,
          awayTeamGoals: 0,
          category: 'NORMAL',
          startTime: 2400,
          endTime: 3600,
        },
        {
          index: 4,
          homeTeamGoals: 0,
          awayTeamGoals: 0,
          category: 'OVERTIME',
          startTime: 3600,
          endTime: 3900,
        },
        {
          index: 5,
          homeTeamGoals: 0,
          awayTeamGoals: 0,
          category: 'WINNING_SHOT_COMPETITION',
          startTime: 3900,
          endTime: 3900,
        },
      ],
      finishedType: 'ENDED_DURING_REGULAR_GAME_TIME',
      started: true,
      ended: false,
      gameTime: 0,
      spectators: 4447,
      referees: [
        {
          firstName: 'PETRI',
          jersey: 14,
          lastName: 'LINDQVIST',
          officialID: 22422200,
          roleAbbrv: 'PT',
          roleName: 'Päätuomari',
          secondaryID: 0,
          tagA: null,
          tagB: null,
          pictureUrl:
            'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/referees/22422200/picture',
        },
        {
          firstName: 'JERE',
          jersey: 61,
          lastName: 'KOSKELA',
          officialID: 24563701,
          roleAbbrv: 'LT',
          roleName: 'Linjatuomari',
          secondaryID: 0,
          tagA: null,
          tagB: null,
          pictureUrl:
            'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/referees/24563701/picture',
        },
        {
          firstName: 'HANNU',
          jersey: 53,
          lastName: 'SORMUNEN',
          officialID: 25531952,
          roleAbbrv: 'LT',
          roleName: 'Linjatuomari',
          secondaryID: 0,
          tagA: null,
          tagB: null,
          pictureUrl:
            'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/referees/25531952/picture',
        },
        {
          firstName: 'JANI',
          jersey: 12,
          lastName: 'LUOMA-AHO',
          officialID: 24754578,
          roleAbbrv: 'PT',
          roleName: 'Päätuomari',
          secondaryID: 0,
          tagA: null,
          tagB: null,
          pictureUrl:
            'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/referees/24754578/picture',
        },
      ],
      cacheUpdateDate: '2021-12-23T08:30:08.304545Z',
    },
  ],
};

const liveGamesOneGoal = {
  games: [
    {
      id: 1337,
      season: 2022,
      start: '2021-12-20T16:30:00Z',
      homeTeam: {
        teamId: '362185137:tappara',
        teamPlaceholder: null,
        goals: 1,
        timeOut: null,
        goalEvents: [
          {
            scorerPlayerId: 28262723,
            logTime: '2021-12-20T16:41:35Z',
            winningGoal: false,
            gameTime: 149,
            period: 1,
            eventId: 16,
            goalTypes: [],
            assistantPlayerIds: [22842712, 24622477],
            plusPlayerIds: '11 52 63 71 81',
            minusPlayerIds: '20 26 34 42 90',
            homeTeamScore: 1,
            awayTeamScore: 0,
            assistsSoFarInSeason: {
              22842712: 1,
              24622477: 18,
            },
            goalsSoFarInSeason: 11,
            videoClipUrl:
              'https://www.katsomo.fi/multimedia/verkostoplayer/player.html?assetId=1528144',
            videoThumbnailUrl:
              'https://image.katsomo.fi/api/v2/img/61c0b5fee4b0504a93ea5f96-1640019455314?impolicy=scale&mtvwidth540=&mtvheight=540',
          },
        ],
        penaltyEvents: [
          {
            playerId: 28745305,
            suffererPlayerId: 28745305,
            logTime: '2021-12-20T16:37:43Z',
            gameTime: 205,
            period: 1,
            penaltyBegintime: 205,
            penaltyEndtime: 325,
            penaltyFaultName: 'Kampitus',
            penaltyFaultType: 'KAM',
            penaltyInfo: '',
            penaltyMinutes: 2,
          },
          {
            playerId: 28262723,
            suffererPlayerId: 28262723,
            logTime: '2021-12-20T17:23:11Z',
            gameTime: 1386,
            period: 2,
            penaltyBegintime: 1386,
            penaltyEndtime: 1506,
            penaltyFaultName: 'Koukkaaminen',
            penaltyFaultType: 'KOU',
            penaltyInfo: '',
            penaltyMinutes: 2,
          },
        ],
        goalKeeperEvents: [],
        goalKeeperChanges: [],
        powerplayInstances: 3,
        powerplayGoals: 0,
        shortHandedInstances: 2,
        shortHandedGoals: 0,
      },
      awayTeam: {
        teamId: '859884935:kalpa',
        teamPlaceholder: null,
        goals: 0,
        timeOut: 3436,
        goalEvents: [],
        penaltyEvents: [
          {
            playerId: 31110600,
            suffererPlayerId: 31110600,
            logTime: '2021-12-20T16:40:56Z',
            gameTime: 318,
            period: 1,
            penaltyBegintime: 318,
            penaltyEndtime: 438,
            penaltyFaultName: 'Koukkaaminen',
            penaltyFaultType: 'KOU',
            penaltyInfo: '',
            penaltyMinutes: 2,
          },
          {
            playerId: 25057054,
            suffererPlayerId: 25057054,
            logTime: '2021-12-20T17:29:03Z',
            gameTime: 1648,
            period: 2,
            penaltyBegintime: 1648,
            penaltyEndtime: 1768,
            penaltyFaultName: 'Huitominen',
            penaltyFaultType: 'HUI',
            penaltyInfo: '',
            penaltyMinutes: 2,
          },
          {
            playerId: 24558127,
            suffererPlayerId: 24558127,
            logTime: '2021-12-20T18:52:54Z',
            gameTime: 2326,
            period: 2,
            penaltyBegintime: 2326,
            penaltyEndtime: 2446,
            penaltyFaultName: 'Kampitus',
            penaltyFaultType: 'KAM',
            penaltyInfo: '',
            penaltyMinutes: 2,
          },
        ],
        goalKeeperEvents: [
          {
            playerId: 60328138,
            beginTime: 3436,
            emptyNet: 1,
            endTime: 3539,
            logTime: '2021-12-20T18:39:03Z',
            gameTime: 3436,
            period: 3,
          },
          {
            playerId: 60328138,
            beginTime: 3539,
            emptyNet: 0,
            endTime: 3600,
            logTime: '2021-12-20T18:40:00Z',
            gameTime: 3539,
            period: 3,
          },
        ],
        goalKeeperChanges: [],
        powerplayInstances: 2,
        powerplayGoals: 0,
        shortHandedInstances: 3,
        shortHandedGoals: 0,
      },
      winningShotCompetitionEvents: [],
      periods: [
        {
          index: 1,
          homeTeamGoals: 2,
          awayTeamGoals: 0,
          category: 'NORMAL',
          startTime: 0,
          endTime: 1200,
        },
        {
          index: 2,
          homeTeamGoals: 1,
          awayTeamGoals: 2,
          category: 'NORMAL',
          startTime: 1200,
          endTime: 2400,
        },
        {
          index: 3,
          homeTeamGoals: 1,
          awayTeamGoals: 0,
          category: 'NORMAL',
          startTime: 2400,
          endTime: 3600,
        },
        {
          index: 4,
          homeTeamGoals: 0,
          awayTeamGoals: 0,
          category: 'OVERTIME',
          startTime: 3600,
          endTime: 3900,
        },
        {
          index: 5,
          homeTeamGoals: 0,
          awayTeamGoals: 0,
          category: 'WINNING_SHOT_COMPETITION',
          startTime: 3900,
          endTime: 3900,
        },
      ],
      finishedType: 'ENDED_DURING_REGULAR_GAME_TIME',
      started: true,
      ended: false,
      gameTime: 149,
      spectators: 4447,
      referees: [
        {
          firstName: 'PETRI',
          jersey: 14,
          lastName: 'LINDQVIST',
          officialID: 22422200,
          roleAbbrv: 'PT',
          roleName: 'Päätuomari',
          secondaryID: 0,
          tagA: null,
          tagB: null,
          pictureUrl:
            'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/referees/22422200/picture',
        },
        {
          firstName: 'JERE',
          jersey: 61,
          lastName: 'KOSKELA',
          officialID: 24563701,
          roleAbbrv: 'LT',
          roleName: 'Linjatuomari',
          secondaryID: 0,
          tagA: null,
          tagB: null,
          pictureUrl:
            'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/referees/24563701/picture',
        },
        {
          firstName: 'HANNU',
          jersey: 53,
          lastName: 'SORMUNEN',
          officialID: 25531952,
          roleAbbrv: 'LT',
          roleName: 'Linjatuomari',
          secondaryID: 0,
          tagA: null,
          tagB: null,
          pictureUrl:
            'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/referees/25531952/picture',
        },
        {
          firstName: 'JANI',
          jersey: 12,
          lastName: 'LUOMA-AHO',
          officialID: 24754578,
          roleAbbrv: 'PT',
          roleName: 'Päätuomari',
          secondaryID: 0,
          tagA: null,
          tagB: null,
          pictureUrl:
            'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/referees/24754578/picture',
        },
      ],
      cacheUpdateDate: '2021-12-23T08:30:08.304545Z',
    },
  ],
};

const upcomingGames = [
  {
    id: 1337,
    season: 2022,
    start: '2022-01-12T16:30:00Z',
    homeTeam: {
      teamId: '362185137:tappara',
      teamPlaceholder: null,
      goals: 0,
      timeOut: null,
      powerplayInstances: 0,
      powerplayGoals: 0,
      shortHandedInstances: 0,
      shortHandedGoals: 0,
    },
    awayTeam: {
      teamId: '859884935:kalpa',
      teamPlaceholder: null,
      goals: 0,
      timeOut: null,
      powerplayInstances: 0,
      powerplayGoals: 0,
      shortHandedInstances: 0,
      shortHandedGoals: 0,
    },
    finishedType: 'ACTIVE_OR_NOT_STARTED',
    started: false,
    ended: false,
    buyTicketsUrl: 'https://tappara.lippu.fi/',
    stale: false,
  },
];

const singleGame = {
  game: {
    id: 1337,
    season: 2022,
    start: '2021-12-20T16:30:00Z',
    homeTeam: {
      teamId: '362185137:tappara',
      teamPlaceholder: null,
      goals: 0,
      timeOut: null,
      goalEvents: [],
      penaltyEvents: [],
      goalKeeperEvents: [],
      goalKeeperChanges: [],
      powerplayInstances: 0,
      powerplayGoals: 0,
      shortHandedInstances: 0,
      shortHandedGoals: 0,
    },
    awayTeam: {
      teamId: '859884935:kalpa',
      teamPlaceholder: null,
      goals: 0,
      timeOut: null,
      goalEvents: [],
      penaltyEvents: [],
      goalKeeperEvents: [],
      goalKeeperChanges: [],
      powerplayInstances: 0,
      powerplayGoals: 0,
      shortHandedInstances: 0,
      shortHandedGoals: 0,
    },
    winningShotCompetitionEvents: [],
    periods: [
      {
        index: 1,
        homeTeamGoals: 0,
        awayTeamGoals: 0,
        category: 'NORMAL',
        startTime: 0,
        endTime: 1200,
      },
      {
        index: 2,
        homeTeamGoals: 0,
        awayTeamGoals: 0,
        category: 'NORMAL',
        startTime: 1200,
        endTime: 2400,
      },
      {
        index: 3,
        homeTeamGoals: 0,
        awayTeamGoals: 0,
        category: 'NORMAL',
        startTime: 2400,
        endTime: 3600,
      },
      {
        index: 4,
        homeTeamGoals: 0,
        awayTeamGoals: 0,
        category: 'OVERTIME',
        startTime: 3600,
        endTime: 3900,
      },
      {
        index: 5,
        homeTeamGoals: 0,
        awayTeamGoals: 0,
        category: 'WINNING_SHOT_COMPETITION',
        startTime: 3900,
        endTime: 3900,
      },
    ],
    finishedType: 'ENDED_DURING_REGULAR_GAME_TIME',
    started: false,
    ended: false,
    gameTime: 0,
    spectators: 4447,
    referees: [
      {
        firstName: 'PETRI',
        jersey: 14,
        lastName: 'LINDQVIST',
        officialID: 22422200,
        roleAbbrv: 'PT',
        roleName: 'Päätuomari',
        secondaryID: 0,
        tagA: null,
        tagB: null,
        pictureUrl:
          'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/referees/22422200/picture',
      },
      {
        firstName: 'JERE',
        jersey: 61,
        lastName: 'KOSKELA',
        officialID: 24563701,
        roleAbbrv: 'LT',
        roleName: 'Linjatuomari',
        secondaryID: 0,
        tagA: null,
        tagB: null,
        pictureUrl:
          'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/referees/24563701/picture',
      },
      {
        firstName: 'HANNU',
        jersey: 53,
        lastName: 'SORMUNEN',
        officialID: 25531952,
        roleAbbrv: 'LT',
        roleName: 'Linjatuomari',
        secondaryID: 0,
        tagA: null,
        tagB: null,
        pictureUrl:
          'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/referees/25531952/picture',
      },
      {
        firstName: 'JANI',
        jersey: 12,
        lastName: 'LUOMA-AHO',
        officialID: 24754578,
        roleAbbrv: 'PT',
        roleName: 'Päätuomari',
        secondaryID: 0,
        tagA: null,
        tagB: null,
        pictureUrl:
          'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/referees/24754578/picture',
      },
    ],
    cacheUpdateDate: '2022-01-03T18:31:53.815223Z',
    stale: false,
  },
  awards: [],
  homeTeamPlayers: [
    {
      id: 33502782,
      teamId: '362185137:tappara',
      line: 1,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Helsinki',
      dateOfBirth: '2001-07-01',
      nationality: 'FIN',
      firstName: 'KARI',
      lastName: 'PIIROINEN',
      role: 'GOALIE',
      handedness: 'LEFT',
      height: 186,
      weight: 80,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 1,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/33502782/picture',
    },
    {
      id: 34254136,
      teamId: '362185137:tappara',
      line: 1,
      countryOfBirth: 'FRA',
      placeOfBirth: 'Saint Maurice',
      dateOfBirth: '1991-02-05',
      nationality: 'FRA',
      firstName: 'CHARLES',
      lastName: 'BERTRAND',
      role: 'RIGHT_WING',
      handedness: 'RIGHT',
      height: 185,
      weight: 94,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 9,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/34254136/picture',
    },
    {
      id: 28262723,
      teamId: '362185137:tappara',
      line: 3,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Hämeenlinna',
      dateOfBirth: '1996-03-06',
      nationality: 'FIN',
      firstName: 'PATRIK',
      lastName: 'VIRTA',
      role: 'CENTER',
      handedness: 'RIGHT',
      height: 177,
      weight: 82,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 11,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/28262723/picture',
    },
    {
      id: 29798827,
      teamId: '362185137:tappara',
      line: 4,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Tampere',
      dateOfBirth: '1998-07-06',
      nationality: 'FIN',
      firstName: 'WALTTERI',
      lastName: 'MERELÄ',
      role: 'RIGHT_WING',
      handedness: 'RIGHT',
      height: 188,
      weight: 89,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 19,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/29798827/picture',
    },
    {
      id: 32935444,
      teamId: '362185137:tappara',
      line: 2,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Joensuu',
      dateOfBirth: '2003-01-31',
      nationality: 'FIN',
      firstName: 'PAAVO',
      lastName: 'KOHONEN',
      role: 'GOALIE',
      handedness: 'LEFT',
      height: 184,
      weight: 73,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 23,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/32935444/picture',
    },
    {
      id: 31854445,
      teamId: '362185137:tappara',
      line: 2,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Tampere',
      dateOfBirth: '2000-08-17',
      nationality: 'FIN',
      firstName: 'KRISTIAN',
      lastName: 'TANUS',
      role: 'RIGHT_WING',
      handedness: 'LEFT',
      height: 172,
      weight: 72,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 27,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/31854445/picture',
    },
    {
      id: 25113804,
      teamId: '362185137:tappara',
      line: 4,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Ylöjärvi',
      dateOfBirth: '1995-04-12',
      nationality: 'FIN',
      firstName: 'OTTO',
      lastName: 'RAUHALA',
      role: 'CENTER',
      handedness: 'LEFT',
      height: 180,
      weight: 90,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 42,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/25113804/picture',
    },
    {
      id: 29942725,
      teamId: '362185137:tappara',
      line: 3,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Tampere',
      dateOfBirth: '1999-11-13',
      nationality: 'FIN',
      firstName: 'SAKU',
      lastName: 'SALMINEN',
      role: 'LEFT_DEFENSEMAN',
      handedness: 'LEFT',
      height: 184,
      weight: 88,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 50,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/29942725/picture',
    },
    {
      id: 23000702,
      teamId: '362185137:tappara',
      line: 1,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Helsinki',
      dateOfBirth: '1993-11-19',
      nationality: 'FIN',
      firstName: 'OTSO',
      lastName: 'RANTAKARI',
      role: 'RIGHT_DEFENSEMAN',
      handedness: 'RIGHT',
      height: 184,
      weight: 82,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 52,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/23000702/picture',
    },
    {
      id: 24509817,
      teamId: '362185137:tappara',
      line: 2,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Helsinki',
      dateOfBirth: '1994-12-26',
      nationality: 'FIN',
      firstName: 'CASIMIR',
      lastName: 'JURGENS',
      role: 'LEFT_DEFENSEMAN',
      handedness: 'LEFT',
      height: 182,
      weight: 82,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 61,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/24509817/picture',
    },
    {
      id: 23517198,
      teamId: '362185137:tappara',
      line: 1,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Hämeenlinna',
      dateOfBirth: '1996-01-01',
      nationality: 'FIN',
      firstName: 'JONI',
      lastName: 'TUULOLA',
      role: 'LEFT_DEFENSEMAN',
      handedness: 'LEFT',
      height: 191,
      weight: 84,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 63,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/23517198/picture',
    },
    {
      id: 28745305,
      teamId: '362185137:tappara',
      line: 2,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Lempäälä',
      dateOfBirth: '1997-09-26',
      nationality: 'FIN',
      firstName: 'JOONA',
      lastName: 'LUOTO',
      role: 'LEFT_WING',
      handedness: 'LEFT',
      height: 190,
      weight: 87,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 68,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/28745305/picture',
    },
    {
      id: 24622477,
      teamId: '362185137:tappara',
      line: 3,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Seinäjoki',
      dateOfBirth: '1983-02-19',
      nationality: 'FIN',
      firstName: 'KRISTIAN',
      lastName: 'KUUSELA',
      role: 'RIGHT_WING',
      handedness: 'RIGHT',
      height: 175,
      weight: 84,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 71,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/24622477/picture',
    },
    {
      id: 29933776,
      teamId: '362185137:tappara',
      line: 2,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Lahti',
      dateOfBirth: '1999-03-25',
      nationality: 'FIN',
      firstName: 'SANTTU',
      lastName: 'KINNUNEN',
      role: 'RIGHT_DEFENSEMAN',
      handedness: 'RIGHT',
      height: 187,
      weight: 73,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 72,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/29933776/picture',
    },
    {
      id: 27746619,
      teamId: '362185137:tappara',
      line: 4,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Varkaus',
      dateOfBirth: '1995-11-28',
      nationality: 'FIN',
      firstName: 'ANTON',
      lastName: 'LEVTCHI',
      role: 'LEFT_WING',
      handedness: 'LEFT',
      height: 182,
      weight: 84,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 76,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/27746619/picture',
    },
    {
      id: 22842712,
      teamId: '362185137:tappara',
      line: 3,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Tampere',
      dateOfBirth: '1987-08-26',
      nationality: 'FIN',
      firstName: 'JUKKA',
      lastName: 'PELTOLA',
      role: 'LEFT_WING',
      handedness: 'LEFT',
      height: 184,
      weight: 82,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 81,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/22842712/picture',
    },
    {
      id: 100033593,
      teamId: '362185137:tappara',
      line: 1,
      countryOfBirth: 'CAN',
      placeOfBirth: 'Burnaby, BC',
      dateOfBirth: '1991-12-19',
      nationality: 'CAN',
      firstName: 'TYLER',
      lastName: 'MORLEY',
      role: 'CENTER',
      handedness: 'LEFT',
      height: 173,
      weight: 81,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 86,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/100033593/picture',
    },
    {
      id: 60348367,
      teamId: '362185137:tappara',
      line: 2,
      countryOfBirth: 'CAN',
      placeOfBirth: 'Waterloo, ON',
      dateOfBirth: '1995-03-04',
      nationality: 'CAN',
      firstName: 'KYLE',
      lastName: 'PLATZER',
      role: 'CENTER',
      handedness: 'RIGHT',
      height: 181,
      weight: 80,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 88,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/60348367/picture',
    },
    {
      id: 100034138,
      teamId: '362185137:tappara',
      line: 3,
      countryOfBirth: 'CZE',
      placeOfBirth: 'Praha',
      dateOfBirth: '2004-03-09',
      nationality: 'CZE',
      firstName: 'TOMAS',
      lastName: 'HAMARA',
      role: 'RIGHT_DEFENSEMAN',
      handedness: 'LEFT',
      height: 182,
      weight: 84,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 90,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/100034138/picture',
    },
    {
      id: 30821864,
      teamId: '362185137:tappara',
      line: 1,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Pyhäjoki',
      dateOfBirth: '2001-04-11',
      nationality: 'FIN',
      firstName: 'PETTERI',
      lastName: 'PUHAKKA',
      role: 'LEFT_WING',
      handedness: 'LEFT',
      height: 179,
      weight: 77,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 91,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/30821864/picture',
    },
    {
      id: 29846355,
      teamId: '362185137:tappara',
      line: 4,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Sipoo',
      dateOfBirth: '1999-01-22',
      nationality: 'FIN',
      firstName: 'SAMI',
      lastName: 'MOILANEN',
      role: 'RIGHT_DEFENSEMAN',
      handedness: 'LEFT',
      height: 175,
      weight: 82,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 96,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/29846355/picture',
    },
  ],
  awayTeamPlayers: [
    {
      id: 30951530,
      teamId: '859884935:kalpa',
      line: 2,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Kuopio',
      dateOfBirth: '1999-03-05',
      nationality: 'FIN',
      firstName: 'JOONA',
      lastName: 'RIEKKINEN',
      role: 'LEFT_DEFENSEMAN',
      handedness: 'LEFT',
      height: 180,
      weight: 92,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 6,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/30951530/picture',
    },
    {
      id: 33863780,
      teamId: '859884935:kalpa',
      line: 4,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Kuopio',
      dateOfBirth: '2002-08-24',
      nationality: 'FIN',
      firstName: 'ELIAS',
      lastName: 'KOPONEN',
      role: 'LEFT_WING',
      handedness: 'LEFT',
      height: 178,
      weight: 87,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 15,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/33863780/picture',
    },
    {
      id: 32873373,
      teamId: '859884935:kalpa',
      line: 4,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Kuopio',
      dateOfBirth: '2001-10-29',
      nationality: 'FIN',
      firstName: 'ANDREAS',
      lastName: 'OKANY',
      role: 'CENTER',
      handedness: 'LEFT',
      height: 177,
      weight: 67,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 16,
      pictureUrl: null,
    },
    {
      id: 31110600,
      teamId: '859884935:kalpa',
      line: 2,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Ylivieska',
      dateOfBirth: '2001-07-11',
      nationality: 'FIN',
      firstName: 'BENJAMIN',
      lastName: 'KORHONEN',
      role: 'CENTER',
      handedness: 'LEFT',
      height: 183,
      weight: 80,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 17,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/31110600/picture',
    },
    {
      id: 40431875,
      teamId: '859884935:kalpa',
      line: 1,
      countryOfBirth: 'FRA',
      placeOfBirth: 'Amiens',
      dateOfBirth: '1997-06-20',
      nationality: 'FRA',
      firstName: 'HUGO',
      lastName: 'GALLET',
      role: 'LEFT_DEFENSEMAN',
      handedness: 'LEFT',
      height: 192,
      weight: 94,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 18,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/40431875/picture',
    },
    {
      id: 24558127,
      teamId: '859884935:kalpa',
      line: 1,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Kuopio',
      dateOfBirth: '1986-10-07',
      nationality: 'FIN',
      firstName: 'TUOMAS',
      lastName: 'KIISKINEN',
      role: 'RIGHT_WING',
      handedness: 'LEFT',
      height: 174,
      weight: 78,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 19,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/24558127/picture',
    },
    {
      id: 27471447,
      teamId: '859884935:kalpa',
      line: 3,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Kuhmo',
      dateOfBirth: '1999-02-17',
      nationality: 'FIN',
      firstName: 'ALEKSI',
      lastName: 'KLEMETTI',
      role: 'RIGHT_WING',
      handedness: 'LEFT',
      height: 171,
      weight: 72,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 20,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/27471447/picture',
    },
    {
      id: 28696276,
      teamId: '859884935:kalpa',
      line: 3,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Tampere',
      dateOfBirth: '1997-10-09',
      nationality: 'FIN',
      firstName: 'JESPER',
      lastName: 'MATTILA',
      role: 'LEFT_DEFENSEMAN',
      handedness: 'LEFT',
      height: 180,
      weight: 80,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 26,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/28696276/picture',
    },
    {
      id: 60328138,
      teamId: '859884935:kalpa',
      line: 1,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Vantaa',
      dateOfBirth: '2003-01-27',
      nationality: 'FIN',
      firstName: 'JAMI',
      lastName: 'PASANEN',
      role: 'GOALIE',
      handedness: 'LEFT',
      height: 191,
      weight: 73,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 32,
      pictureUrl: null,
    },
    {
      id: 32306811,
      teamId: '859884935:kalpa',
      line: 3,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Tuusniemi',
      dateOfBirth: '2000-06-21',
      nationality: 'FIN',
      firstName: 'SEVERI',
      lastName: 'IMMONEN',
      role: 'CENTER',
      handedness: 'LEFT',
      height: 180,
      weight: 81,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 34,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/32306811/picture',
    },
    {
      id: 31046431,
      teamId: '859884935:kalpa',
      line: 2,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Leppävirta',
      dateOfBirth: '2000-11-14',
      nationality: 'FIN',
      firstName: 'KIM',
      lastName: 'NOUSIAINEN',
      role: 'RIGHT_DEFENSEMAN',
      handedness: 'LEFT',
      height: 175,
      weight: 81,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 39,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/31046431/picture',
    },
    {
      id: 40191761,
      teamId: '859884935:kalpa',
      line: 2,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Kuopio',
      dateOfBirth: '2004-07-28',
      nationality: 'FIN',
      firstName: 'MILO',
      lastName: 'MARTTINEN',
      role: 'GOALIE',
      handedness: 'LEFT',
      height: 190,
      weight: 78,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 40,
      pictureUrl: null,
    },
    {
      id: 24226640,
      teamId: '859884935:kalpa',
      line: 1,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Kuopio',
      dateOfBirth: '1998-06-11',
      nationality: 'FIN',
      firstName: 'JUUSO',
      lastName: 'KÖNÖNEN',
      role: 'LEFT_WING',
      handedness: 'LEFT',
      height: 182,
      weight: 86,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 41,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/24226640/picture',
    },
    {
      id: 33866651,
      teamId: '859884935:kalpa',
      line: 3,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Kuopio',
      dateOfBirth: '2003-09-29',
      nationality: 'FIN',
      firstName: 'KONSTA',
      lastName: 'KAPANEN',
      role: 'LEFT_WING',
      handedness: 'LEFT',
      height: 170,
      weight: 64,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 42,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/33866651/picture',
    },
    {
      id: 60499751,
      teamId: '859884935:kalpa',
      line: 4,
      countryOfBirth: 'SWE',
      placeOfBirth: 'Göteborg',
      dateOfBirth: '2001-01-08',
      nationality: 'SWE',
      firstName: 'ERIC',
      lastName: 'HJORTH',
      role: 'RIGHT_DEFENSEMAN',
      handedness: 'RIGHT',
      height: 192,
      weight: 88,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 45,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/60499751/picture',
    },
    {
      id: 28942315,
      teamId: '859884935:kalpa',
      line: 4,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Vantaa',
      dateOfBirth: '1998-08-23',
      nationality: 'FIN',
      firstName: 'ROOPE',
      lastName: 'LAAVAINEN',
      role: 'RIGHT_WING',
      handedness: 'RIGHT',
      height: 187,
      weight: 91,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 52,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/28942315/picture',
    },
    {
      id: 24725109,
      teamId: '859884935:kalpa',
      line: 1,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Kuopio',
      dateOfBirth: '1989-06-07',
      nationality: 'FIN',
      firstName: 'LASSE',
      lastName: 'LAPPALAINEN',
      role: 'RIGHT_DEFENSEMAN',
      handedness: 'LEFT',
      height: 190,
      weight: 93,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 55,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/24725109/picture',
    },
    {
      id: 25057054,
      teamId: '859884935:kalpa',
      line: 2,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Kuopio',
      dateOfBirth: '1996-04-27',
      nationality: 'FIN',
      firstName: 'MIIKKA',
      lastName: 'PITKÄNEN',
      role: 'LEFT_WING',
      handedness: 'LEFT',
      height: 177,
      weight: 75,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 61,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/25057054/picture',
    },
    {
      id: 21851458,
      teamId: '859884935:kalpa',
      line: 1,
      countryOfBirth: 'GBR',
      placeOfBirth: 'Lontoo',
      dateOfBirth: '1989-10-14',
      nationality: 'FIN',
      firstName: 'MATTI',
      lastName: 'JÄRVINEN',
      role: 'CENTER',
      handedness: 'LEFT',
      height: 195,
      weight: 97,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 71,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/21851458/picture',
    },
    {
      id: 40024585,
      teamId: '859884935:kalpa',
      line: 2,
      countryOfBirth: 'FRA',
      placeOfBirth: 'Ambilly',
      dateOfBirth: '1997-04-25',
      nationality: 'FIN',
      firstName: 'SAMI',
      lastName: 'TAVERNIER',
      role: 'RIGHT_WING',
      handedness: 'RIGHT',
      height: 182,
      weight: 80,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 74,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/40024585/picture',
    },
    {
      id: 23167645,
      teamId: '859884935:kalpa',
      line: 3,
      countryOfBirth: 'FIN',
      placeOfBirth: 'Helsinki',
      dateOfBirth: '1990-05-16',
      nationality: 'FIN',
      firstName: 'SAKU',
      lastName: 'SALMELA',
      role: 'RIGHT_DEFENSEMAN',
      handedness: 'LEFT',
      height: 176,
      weight: 84,
      captain: false,
      rookie: false,
      alternateCaptain: false,
      jersey: 90,
      pictureUrl:
        'https://prod.liiga-mobile.starcloud.us/mobile-backend/api/v1/players/23167645/picture',
    },
  ],
};

module.exports = {
  liveGames: liveGamesNoGoal,
  singleGame,
  upcomingGames,
};
