services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    container_name: reverse-proxy
  todo-frontend:
    image: frontend
    build: ./todo-frontend
    ports:
      - 3000:80
    environment:
      - REACT_APP_BACKEND_URL=/api
    container_name: frontend
  todo-backend:
    image: backend
    build: ./todo-backend
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    container_name: backend
  mongo:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
    container_name: mongo
  redis:
    image: redis
    ports:
    - 6378:6379
    command: ['redis-server', '--appendonly', 'yes'] # Overwrite the CMD
    volumes:
      - ./todo-backend/redis_data:/data
    container_name: redis